### ISSUE TITLE
Add a PolicySetIdReference to a PolicySet

### ISSUE THREAD

**Issue by Joao-Parente** [authzforce/java-xacml-sdk#35]
I have been experimenting with the "[authzforce-xacmlsdk-samples](https://github.com/authzforce/java-xacml-sdk/tree/master/authzforce-xacmlsdk-samples)", and i'm trying to create a PolicySet that has an PolicySetIdReference.

I searched the oasis.names.tc.xacml._3_0.core.schema.wd_17 and found out that there is no class PolicySetIdReference, but there is a class IdReferenceType, that is the type of the PolicySetIdReference according to the xacml 3.0 specification(http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html).

So, when i try to create a PolicySet and insert the IdReference it returns an error.

Code:
```
 AdminXacmlSdk client = new AdminXacmlSdkImpl(URI.create(http://127.0.0.1:8080/authzforce-ce/));
 
 IdReferenceType idReferenceType = new IdReferenceType("idOfAnotherPolicy",null,null,null);
 List<Object> obj = new ArrayList<>();obj.add(idReferenceType);    
 PolicySet set = client.createSimplePolicy(DOMAIN_ID, "myTestPolicy", "Test policy", obj);
 
 client.addPolicy(DOMAIN_ID, set);
 ```
 
Error: 
```
Exception in thread "main" org.ow2.authzforce.sdk.exceptions.XacmlSdkException: org.apache.cxf.interceptor.Fault: No message body writer has been found for class oasis.names.tc.xacml._3_0.core.schema.wd_17.PolicySet, ContentType: application/xml
	at org.ow2.authzforce.sdk.impl.AdminXacmlSdkImpl.addPolicy(AdminXacmlSdkImpl.java:127)
	at PapAteste.main(PapAteste.java:54)
Caused by: org.apache.cxf.interceptor.Fault: No message body writer has been found for class oasis.names.tc.xacml._3_0.core.schema.wd_17.PolicySet, ContentType: application/xml
	at org.apache.cxf.jaxrs.client.ClientProxyImpl$BodyWriter.doWriteBody(ClientProxyImpl.java:828)
	at org.apache.cxf.jaxrs.client.AbstractClient$AbstractBodyWriter.handleMessage(AbstractClient.java:1043)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:624)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:688)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:227)
	at com.sun.proxy.$Proxy22.addPolicy(Unknown Source)
	at org.ow2.authzforce.sdk.impl.AdminXacmlSdkImpl.addPolicy(AdminXacmlSdkImpl.java:119)
	... 1 more
Caused by: javax.ws.rs.ProcessingException: No message body writer has been found for class oasis.names.tc.xacml._3_0.core.schema.wd_17.PolicySet, ContentType: application/xml
	at org.apache.cxf.jaxrs.client.AbstractClient.reportMessageHandlerProblem(AbstractClient.java:742)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:470)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl$BodyWriter.doWriteBody(ClientProxyImpl.java:818)
	... 8 more
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.apache.cxf.jaxrs.utils.SpecExceptions.toInternalServerErrorException(SpecExceptions.java:79)
	at org.apache.cxf.jaxrs.utils.ExceptionUtils.toInternalServerErrorException(ExceptionUtils.java:106)
	at org.apache.cxf.jaxrs.provider.AbstractJAXBProvider.handleExceptionEnd(AbstractJAXBProvider.java:705)
	at org.apache.cxf.jaxrs.provider.AbstractJAXBProvider.handleJAXBException(AbstractJAXBProvider.java:729)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.writeTo(JAXBElementProvider.java:321)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1375)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:456)
	... 9 more
Caused by: com.sun.istack.SAXException2: unable to marshal type "oasis.names.tc.xacml._3_0.core.schema.wd_17.IdReferenceType" as an element because it is missing an @XmlRootElement annotation
	at com.sun.xml.bind.v2.runtime.XMLSerializer.reportError(XMLSerializer.java:249)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:338)
	at com.sun.xml.bind.v2.runtime.property.ArrayReferenceNodeProperty.serializeListBody(ArrayReferenceNodeProperty.java:118)
	at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:159)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:360)
	at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:593)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:341)
	at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:494)
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:328)
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:256)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:110)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.marshalToOutputStream(JAXBElementProvider.java:624)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.marshal(JAXBElementProvider.java:581)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.marshal(JAXBElementProvider.java:444)
	at org.apache.cxf.jaxrs.provider.JAXBElementProvider.writeTo(JAXBElementProvider.java:318)
	... 11 more

Process finished with exit code 1

```

Is this the correct way to add a PolicySetIdReference to a PolicySet?

**Comment by cdanger** [comment]
Use the XACML/JAXB ObjectFactory to create the PolicySetIdReference, i.e.:
```java
import oasis.names.tc.xacml._3_0.core.schema.wd_17.ObjectFactory;
...
public static final  ObjectFactory XACML_3_0_OBJECT_FACTORY = new oasis.names.tc.xacml._3_0.core.schema.wd_17.ObjectFactory();
```

Then replace ```obj.add(idReferenceType);``` with:
```java
obj.add(XACML_3_0_OBJECT_FACTORY.createPolicySetIdReference(idReferenceType));
```

**Comment by Joao-Parente** [comment]
Thank you, it works.
