### ISSUE TITLE
SAXException2 when creating a reqest with category whose property is created from anything else other than date or string

### ISSUE THREAD

**Issue by DemianTinkiel** [authzforce/java-xacml-sdk#4]
```
LOGGER.info("Testing Request creation");
		subjectCat.addAttribute(new Subject("TestCreateXacmlRequest"));
		resourceCat.addAttribute(new Resource("TestCreateXacmlRequest"));
		actionCategory.addAttribute(new Action("TestCreateXacmlRequest"));
		environmentCategory.addAttribute(new Environment(1));
		final String actualRequest = Utils.createXacmlRequest(Arrays.asList(subjectCat), Arrays.asList(resourceCat), Arrays.asList(actionCategory), Arrays.asList(environmentCategory)).toString();
```
throws
```
[com.sun.istack.internal.SAXException2: unable to marshal type "java.lang.Integer" as an element because it is missing an @XmlRootElement annotation]
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:311)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:116)
	at org.ow2.authzforce.sdk.core.schema.Request.toString(Request.java:57)
```
however if environment is `environmentCategory.addAttribute(new Environment("foo"));` or `environmentCategory.addAttribute(new Environment(new Date()));` then all is well

This affects any of the children of `org.ow2.authzforce.sdk.core.schema.Attribute`

**Comment by DemianTinkiel** [comment]
For what I see this can be fixed with
```
public Environment(final int value) {
		super(Arrays.asList(new AttributeValueType(Arrays.asList((Serializable)String.valueOf(value)), XACMLDatatypes.XACML_DATATYPE_INTEGER.value(), null)), DEFDAULT_ATTRIBUTE_ID.value(), DEFAULT_ISSUER, true);
	}
```
note the `String.valueOf(value)`
